repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-docstring-first
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: fix-encoding-pragma
  - id: requirements-txt-fixer

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: [--profile, black, --filter-files]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.264
  hooks:
  - id: ruff


- repo: https://github.com/commitizen-tools/commitizen
  rev: 3.2.1
  hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - post-commit
    - push
